all:
  children:
    arista:
      hosts:
        ceos1:
          ansible_host: 172.20.20.7
        ceos2:
          ansible_host: 172.20.20.6
        ceos3:
          ansible_host: 172.20.20.4
        ceos4:
          ansible_host: 172.20.20.2
        ceos5:
          ansible_host: 172.20.20.3
        ceos6:
          ansible_host: 172.20.20.5
    cisco:
      hosts:
        rp1:
          ansible_host: 10.10.20.234
          ansible_port: 60001
        rp2:
          ansible_host: 10.10.20.235
          ansible_port: 60002
        rpe1:
          ansible_host: 10.10.20.236
          ansible_port: 60003
        rpe2:
          ansible_host: 10.10.20.237
          ansible_port: 60004
